export const AuctionHashABI = [
  // Read functions
  {
    inputs: [],
    name: "currentAuctionId",
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentAuction",
    outputs: [
      { name: "auctionId", type: "uint256" },
      { name: "startTime", type: "uint256" },
      { name: "endTime", type: "uint256" },
      { name: "jackpot", type: "uint256" },
      { name: "totalBids", type: "uint256" },
      { name: "revealed", type: "bool" },
      { name: "winner", type: "address" },
      { name: "winningBid", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "auctionId", type: "uint256" }],
    name: "getAuctionBids",
    outputs: [
      { name: "bidderList", type: "address[]" },
      { name: "amounts", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "auctionId", type: "uint256" }],
    name: "getSortedBids",
    outputs: [
      { name: "sortedBidders", type: "address[]" },
      { name: "sortedAmounts", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "amount", type: "uint256" }],
    name: "calculateSafeZone",
    outputs: [
      { name: "isValid", type: "bool" },
      { name: "minSafeAmount", type: "uint256" },
      { name: "maxSafeAmount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "auctionId", type: "uint256" },
      { name: "user", type: "address" },
    ],
    name: "hasPendingClaim",
    outputs: [
      { name: "hasClaim", type: "bool" },
      { name: "isWinner", type: "bool" },
      { name: "claimAmount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "fromId", type: "uint256" },
      { name: "count", type: "uint256" },
    ],
    name: "getAuctionHistory",
    outputs: [
      { name: "auctionIds", type: "uint256[]" },
      { name: "winners", type: "address[]" },
      { name: "winningBids", type: "uint256[]" },
      { name: "jackpots", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "uint256" }],
    name: "auctions",
    outputs: [
      { name: "startTime", type: "uint256" },
      { name: "endTime", type: "uint256" },
      { name: "jackpot", type: "uint256" },
      { name: "winner", type: "address" },
      { name: "winningBid", type: "uint256" },
      { name: "revealed", type: "bool" },
      { name: "totalBids", type: "uint256" },
      { name: "revealBlockHash", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    name: "bids",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    name: "invalidated",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    name: "claimed",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxGapPercent",
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "losersRefundPercent",
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "minBid",
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingJackpot",
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "hashToken",
    outputs: [{ type: "address", name: "" }],
    stateMutability: "view",
    type: "function",
  },

  // Write functions
  {
    inputs: [{ name: "amount", type: "uint256" }],
    name: "bid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "reveal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "auctionId", type: "uint256" }],
    name: "claimWinnings",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "auctionId", type: "uint256" }],
    name: "claimRefund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "amount", type: "uint256" }],
    name: "feedJackpot",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },

  // Events
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "auctionId", type: "uint256" },
      { indexed: false, name: "startTime", type: "uint256" },
      { indexed: false, name: "endTime", type: "uint256" },
      { indexed: false, name: "initialJackpot", type: "uint256" },
    ],
    name: "AuctionStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "auctionId", type: "uint256" },
      { indexed: true, name: "bidder", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "previousBid", type: "uint256" },
    ],
    name: "BidPlaced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "auctionId", type: "uint256" },
      { indexed: true, name: "bidder", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "gapPercent", type: "uint256" },
    ],
    name: "BidInvalidated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "auctionId", type: "uint256" },
      { indexed: true, name: "winner", type: "address" },
      { indexed: false, name: "winningBid", type: "uint256" },
      { indexed: false, name: "jackpot", type: "uint256" },
    ],
    name: "WinnerDetermined",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "auctionId", type: "uint256" },
      { indexed: true, name: "bidder", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "wasInvalidated", type: "bool" },
    ],
    name: "RefundClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "auctionId", type: "uint256" },
      { indexed: true, name: "winner", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "WinningsClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "source", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "JackpotFed",
    type: "event",
  },
] as const;
